//var langJSONObject = jQuery.parseJSON('{ "Accessible":"无障碍环境", "Fast":"快速","Compatible":"兼容","Secure":"安全"}');
var langJSONObject = [
    {
        "id": "string00000",
        "msgid": "Accessible",
        "msgstr": "无障碍环境"
    },
    {
        "id": "string00001",
        "msgid": "Fast",
        "msgstr": "快速"
    },
    {
        "id": "string00002",
        "msgid": "Compatible",
        "msgstr": "兼容"
    },
    {
        "id": "string00003",
        "msgid": "Secure",
        "msgstr": "安全"
    }
]
/*var langJSONObject = jQuery.parseJSON('{
 "Accessible":"无障碍环境",
 "Fast":"快速",
 "Compatible":"兼容",
 "Secure":"安全",
 "Your_Ubuntu,_your_way":"你的Ubuntu你作主",
 "Accessibility is central to the Ubuntu philosophy. We believe that computing is for everyone regardless of nationality, race, gender or disability. Fully translated into 38 languages, Ubuntu also includes essential assistive technologies, which are, of course, completely free.":"Ubuntu的核心哲学是其易用性。我们相信计算机是给所有人使用的，不论其民族、性别或是残障与否。完整的被翻译成了25种语言，同时Ubntu也包含了必要的辅助技术，这些都是完全免费的。",
 "Ubuntu loads quickly on any computer, but it's super-fast on newer machines. With no unnecessary programs and trial software slowing things down, booting up and opening a browser takes seconds. Unlike other operating systems that leave you staring at the screen, waiting to get online. And Ubuntu won’t grow sluggish over time. It’s fast. And it stays fast.":"Ubuntu可以在任何电脑上运行，但在最新的机器上会运行的更快。没有什么非必须的和使用软件让您的效率降低，打开一个浏览器只需要几秒。不像其它一些操作系统让 您盯着屏幕等着连上网络。Ubuntu也不会变得越来越慢，很快，而已一直都这样。",
 "Ubuntu works brilliantly with a range of devices. Simply plug in your mp3 player, camera or printer and you’ll be up and running straight away. No installation CDs. No fuss. And it’s compatible with Windows too! So you can open, edit and share Microsoft Office documents stress-free.":"Ubuntu works brilliantly with a range of devices. Simply plug in your mp3 player, camera or printer and you’ll be up and running straight away. No installation CDs. No fuss. And it’s compatible with Windows too! So you can open, edit and share Microsoft Office documents stress-free.",
 "You can surf in safety with Ubuntu – confident that your files and data will stay protected. A built-in firewall and virus protection come as standard. And if a potential threat appears, we provide automatic updates which you can install in a single click. You get added security with AppArmor, which protects your important applications so attackers can’t access your system. And thanks to Firefox and gnome-keyring, Ubuntu helps you keep your private information private. So whether it’s accessing your bank account or sharing sensitive data with friends or colleagues, you’ll have peace of mind when you need it the most.":"You can surf in safety with Ubuntu – confident that your files and data will stay protected. A built-in firewall and virus protection come as standard. And if a potential threat appears, we provide automatic updates which you can install in a single click. You get added security with AppArmor, which protects your important applications so attackers can’t access your system. And thanks to Firefox and gnome-keyring, Ubuntu helps you keep your private information private. So whether it’s accessing your bank account or sharing sensitive data with friends or colleagues, you’ll have peace of mind when you need it the most.",
 "Enjoy the simplicity of Ubuntu's stylish, intuitive interface. Fast, secure and with thousands of apps to choose from, Ubuntu gives you a clean and streamlined experience that you can really make your own.":"Enjoy the simplicity of Ubuntu\"s stylish, intuitive interface. Fast, secure and with thousands of apps to choose from, Ubuntu gives you a clean and streamlined experience that you can really make your own.",
 "Write":"写入",
 "no_subject":"无主题",
 "Recipient":"收件人", 	
 "From":"发件人",
 "Home":"主目录",
 "Desktop":"桌面",
 "Pictures":"图片",
 "Videos":"视频",
 "Music":"音乐",
 "Downloads":"下载",
 "Documents":"文档",
 "Canonical":"Canonical",
 "Backup":"备份",
 "Local":"本地的",
 "work":"work",
 "branches":"分支",
 "Rubbish_bin":"Rubbish bin",
 "Remove":"移除",
 "Free":"空闲",
 "Installed":"已安装",
 "Install":"安装",
 "Installing":"安装中",
 "Chromium_Web_Browser":"Chromium 网页浏览器",
 "Access_the_Internet":"访问互联网",
 "Chromium is an open-source browser project that aims to build a safer, faster, and more stable way for all Internet users to experience the web.<br/><br/>Chromium serves as a base for Google Chrome, which is Chromium rebranded (name and logo) with very few additions such as usage tracking and an auto-updater system.<br/><br/>This package contains the Chromium browser":"Chromium is an open-source browser project that aims to build a safer, faster, and more stable way for all Internet users to experience the web.<br/><br/>Chromium serves as a base for Google Chrome, which is Chromium rebranded (name and logo) with very few additions such as usage tracking and an auto-updater system.<br/><br/>This package contains the Chromium browser",
 "BEEP":"BEEP",
 "A 2D platformer/shooter game with physics-based puzzles":"A 2D platformer/shooter game with physics-based puzzles",
 "BEEP is a 2D side-scrolling platformer with physics-based gameplay. You control a small robot equipped with an anti-gravity device, a jet-pack and a gun. Drive, jump, fly, swim and shoot your way through 24 levels scattered across 6 unique environments.<br/><br/>Use BEEP’s anti-gravity device to directly manipulate the physics-based environments. The anti-gravity device is both a tool and a weapon. Use it to smash enemy robots, build towers and solve puzzles.<br/><br/>BEEP has traveled for thousands of years through deep space to explore the Galaxy. Traverse a foreign star system with the BEEP-ship and send robots to the surface of the planets.":"BEEP is a 2D side-scrolling platformer with physics-based gameplay. You control a small robot equipped with an anti-gravity device, a jet-pack and a gun. Drive, jump, fly, swim and shoot your way through 24 levels scattered across 6 unique environments.<br/><br/>Use BEEP’s anti-gravity device to directly manipulate the physics-based environments. The anti-gravity device is both a tool and a weapon. Use it to smash enemy robots, build towers and solve puzzles.<br/><br/>BEEP has traveled for thousands of years through deep space to explore the Galaxy. Traverse a foreign star system with the BEEP-ship and send robots to the surface of the planets.",
 "Inkscape Vector Graphics Editor":" Inkscape 矢量图形编辑器",
 "Create and edit Scalable Vector Graphics images":"创建并编辑矢量图形文件",
 "Inkscape loads and saves a subset of the SVG (Scalable Vector Graphics) format, a standard maintained by the WWW consortium.<br/><br/>Inkscape user interface should be familiar from CorelDraw and similar drawing programs. There are rectangles, ellipses, text items, bitmap images and freehand curves. As an added bonus, both vector and bitmap objects can have alpha transparency and can be arbitrarily transformed.<br/><br/>Inkscape supports multiple opened files and multiple views per file. Graphics can be printed and exported to png bitmaps.<br/><br/>Some of the import and export features are provided using the packages dia, libwmf-bin, pstoedit, skencil, imagemagick, and perlmagick.<br/><br/>Other extensions use ruby, libxml-xql-perl, python-numpy, and python-lxml. You must have these packages to make full use of all extensions and effects.<br/><br/>If you want to use the spellchecker, you have to install aspell and the respective language-pack, e.g. aspell-en or aspell-de.":"Inkscape loads and saves a subset of the SVG (Scalable Vector Graphics) format, a standard maintained by the WWW consortium.<br/><br/>Inkscape user interface should be familiar from CorelDraw and similar drawing programs. There are rectangles, ellipses, text items, bitmap images and freehand curves. As an added bonus, both vector and bitmap objects can have alpha transparency and can be arbitrarily transformed.<br/><br/>Inkscape supports multiple opened files and multiple views per file. Graphics can be printed and exported to png bitmaps.<br/><br/>Some of the import and export features are provided using the packages dia, libwmf-bin, pstoedit, skencil, imagemagick, and perlmagick.<br/><br/>Other extensions use ruby, libxml-xql-perl, python-numpy, and python-lxml. You must have these packages to make full use of all extensions and effects.<br/><br/>If you want to use the spellchecker, you have to install aspell and the respective language-pack, e.g. aspell-en or aspell-de.",
 "World_of_Goo":"World of Goo",
 "Physics based puzzle/construction game":"Physics based puzzle/construction game",
 "Drag and drop living, squirming, talking globs of goo to build structures, bridges, cannonballs, zeppelins, and giant tongues. The millions of innocent goo balls that live in the beautiful World of Goo are curious to explore.<br/><br/>But they dont know that they are in a game, or that they are extremely delicious. The most addicting and awe-inspiring puzzle game will set you on an adventure that youll never forget!":"Drag and drop living, squirming, talking globs of goo to build structures, bridges, cannonballs, zeppelins, and giant tongues. The millions of innocent goo balls that live in the beautiful World of Goo are curious to explore.<br/><br/>But they dont know that they are in a game, or that they are extremely delicious. The most addicting and awe-inspiring puzzle game will set you on an adventure that youll never forget!",
 "Blender":"Blender",
 "Create and edit 3D models and animations":"创建和编辑三维模型和动画",
 "Blender is an integrated 3d suite for modelling, animation, rendering, post-production, interactive creation and playback (games). Blender has its own particular user interface, which is implemented entirely in OpenGL and designed with speed in mind. Python bindings are available for scripting, import/export features for popular file formats like 3D Studio and Wavefront Obj are implemented as scripts by the community. Stills, animations, models for games or other third party engines and interactive content in the form of a standalone binary and/or a web plug-in are common products of Blender use.":"Blender is an integrated 3d suite for modelling, animation, rendering, post-production, interactive creation and playback (games). Blender has its own particular user interface, which is implemented entirely in OpenGL and designed with speed in mind. Python bindings are available for scripting, import/export features for popular file formats like 3D Studio and Wavefront Obj are implemented as scripts by the community. Stills, animations, models for games or other third party engines and interactive content in the form of a standalone binary and/or a web plug-in are common products of Blender use.",
 "Braid":"Braid",
 "Manipulate the flow of time to solve puzzels":"Manipulate the flow of time to solve puzzels",
 "Manipulate the flow of time to solve puzzles Braid is a platform game in painterly style where you manipulate the flow of time to solve puzzles. Every puzzle in Braid is unique,  there is no filler.<br/><br/>Braid treats your time and attention as precious, and it does everything it can to give you a mind-expanding experience.<br/><br/>All gameplay is based on time manipulation. Journey into worlds where time behaves strangely, observe, learn from, and then master these worlds.":"Manipulate the flow of time to solve puzzles Braid is a platform game in painterly style where you manipulate the flow of time to solve puzzles. Every puzzle in Braid is unique,  there is no filler.<br/><br/>Braid treats your time and attention as precious, and it does everything it can to give you a mind-expanding experience.<br/><br/>All gameplay is based on time manipulation. Journey into worlds where time behaves strangely, observe, learn from, and then master these worlds.",
 "Banshee Media Player":"Banshee Media Player",
 "Brasero Disc Burner":"Brasero Disc Burner",
 "Movie Player":"Movie Player",
 "Shotwell Photo Manager":"Shotwell Photo Manager",
 "PiTiVi Video Editor":"PiTiVi Video Editor",
 "Sound Recorder":"Sound Recorder",
 "Empathy Internet Messageing":"Empathy Internet Messageing",
 "Thunderbird Mail/News":"Thunderbird Mail/News",
 "Firefox Web Browser":"Firefox Web Browser",
 "Gwibber Social Client":"Gwibber Social Client",
 "Remote Desktop Viewer":"Remote Desktop Viewer",
 "Terminal Server Client":"Terminal Server Client",
 "About Me":"About Me",
 "Additional Drivers":"Additional Drivers",
 "AisleRoit Solitaire":"AisleRoit Solitaire",
 "Appearance":"Appearance",
 "Bluetooth":"蓝牙",
 "Search":"Search"
}*/